[SP-11] добавил задачу, которая вычисляет является ли натуральное чис…
BlissBit/prog-study pull request #22
Opened 2021-03-06 22:48 UTC by DarkAngel77792

…ло простым

2021-03-06 23:09 UTC, matyushov requested changes

2021-03-06 23:09 UTC, matyushov commented on dshpilka/sp-11/src/main.cpp
> +	int n, i;
используйте прямую или uniform инициализацию типов, например int value(5); или int value{5};
https://ravesli.com/urok-28-detalnee-ob-initsializatsii-prisvaivanii-i-opredelenii/#toc-3 
а так же отдельно инициализируйте каждую переменную, если используете один стейтмент

2021-03-06 23:11 UTC, matyushov commented on dshpilka/sp-11/src/main.cpp
> +	std::cout << n << std::endl;
зачем пользователю дважды видеть число которое он ввёл?

2021-03-06 23:23 UTC, matyushov commented on dshpilka/sp-11/src/main.cpp
> +
хотелось бы увидеть проверку на ввод символов

2021-03-07 07:46 UTC, AndrewBuhanov approved these changes

2021-03-08 19:22 UTC, matyushov approved these changes

2021-03-09 08:40 UTC, AndrewBuhanov approved these changes

2021-03-09 17:27 UTC, jackee67rus approved these changes

2021-03-09 17:27 UTC, merged