[SP-7] added a program that outputs to the user all the numbers from …
BlissBit/prog-study pull request #26
Opened 2021-03-09 09:44 UTC by AndrewBuhanov

…50 to 100 inclusive, when divided by 7, the remainder is equal to 1,2 or 5

2021-03-09 10:07 UTC, matyushov requested changes

2021-03-09 10:07 UTC, matyushov commented on abuhanov/sp-7/src/division.cpp
> +        if ((i % 7 == 1) || (i % 7 == 2) || (i % 7 == 5))
используй блоки стейтментов

2021-04-09 21:52 UTC, AndrewBuhanov commented on abuhanov/sp-7/src/division.cpp
> +        if ((i % 7 == 1) || (i % 7 == 2) || (i % 7 == 5))
Внёс изменения.
С уважением, Буханов А.Р.

2021-06-04 14:32 UTC, jackee67rus approved these changes

2021-06-08 21:53 UTC, matyushov commented on abuhanov/sp-7/src/division.cpp
> +        if ((i % 7 == 1) || (i % 7 == 2) || (i % 7 == 5))
@AndrewBuhanov изменния неправильные читать Code Style

2021-06-28 20:47 UTC, closed without merging